name: "auditor-action-core"
description: "The Auditor Action's Core"
author: "Grant Birkinbine"
branding:
  icon: "lock"
  color: "gray-dark"
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client - Provided for you by default!
    default: ${{ github.token }}
    required: true
outputs:
  passed:
    description: Whether or not the audit passed - 'true' or 'false'
  violation_count:
    description: The number of violations found
runs:
  using: "node16"
  main: "dist/index.js"
