name: "auditor"
description: "The Auditor"
author: "Grant Birkinbine"
inputs:
  config:
    description: The path to the auditor's config file
    default: config.yml
    required: true
branding:
  icon: "lock"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@v1.0.0
      id: git-diff-action

    - name: save diff results to tmp
      env:
        DIFF_OUTPUT_TMP_DIR: tmp/git-diff-actions/outputs
      run: |
        mkdir -p $DIFF_OUTPUT_TMP_DIR
        echo "${{ steps.git-diff-action.outputs.json-diff }}" > $DIFF_OUTPUT_TMP_DIR/diff.json
      shell: bash

    - name: install node modules
      run: npm install
      shell: bash

    - name: auditor
      run: |
        if [ ! -f tmp/git-diff-actions/outputs/diff.json ]; then
          echo "No diff file found!"
          exit 1
        fi
        export JSON_DIFF=$(cat tmp/git-diff-actions/outputs/diff.json)
        node src/main.js
      env:
        CONFIG: ${{ inputs.config }}
      shell: bash
