name: "auditor"
description: "The Auditor"
author: "Grant Birkinbine"
inputs:
  config:
    description: The path to the auditor's config file
    default: config.yml
    required: true
branding:
  icon: "lock"
  color: "gray-dark"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
      with:
        fetch-depth: 0 # needed to checkout all branches

    - run: echo config path ${{ inputs.config }}
      shell: bash

    - run: cat README.md
      shell: bash
