name: sample-workflow

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # if on pull request
      - uses: ./
        if: github.event_name == 'pull_request'
        with:
          annotate_pr: true
          config_path: config/auditor-sample.yml
          json_diff_path: test/diff-sample-pass.json
