name: sample-workflow

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2

      - uses: ./
        id: the-auditor
        with:
          config: config/the-auditor-sample.yml
