name: sample-workflow

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        id: auditor
